<a href="https://colab.research.google.com/github/penguinman-99/Python_AI/blob/main/MypythonAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


Fri Feb  5 09:40:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    11W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [26]:
import tensorflow as tf
import numpy as np
# string=tf.Variable("this is a string", tf.string)
# number=tf.Variable(324,tf.int16)
# floating=tf.Variable(3.567,tf.float64)
#a=tf.zeros([2,10]) #2행 10열, 0으로 초기화
#b=tf.eye(3) #대각선 값만 1로 고정
print(b)
print(a)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


텐서플로우는 사칙연산을 지원하지만 배열크기와 shape이 같아야 연산가능 

In [18]:
#reduce 함수: 행렬합, 평균, 최대값,최소값 구하기 
a=tf.constant([1,2,3,4,5,6,7,8,9,10])
print(tf.reduce_sum(a))
print(tf.reduce_mean(a))
print(tf.reduce_max(a))
print(tf.reduce_min(a))
c=a+5
print(c)

tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([ 6  7  8  9 10 11 12 13 14 15], shape=(10,), dtype=int32)


In [30]:
#행렬의 곱 계산

first=tf.constant([[1,2,3]])
second=tf.constant([[10],[20],[30]])
c=tf.matmul(first,second)
print(c)
d=tf.add(first,second)
print(d)
#덧셈은 행,열이 모두 같아야한다.


tf.Tensor([[140]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[11 12 13]
 [21 22 23]
 [31 32 33]], shape=(3, 3), dtype=int32)
