<a href="https://colab.research.google.com/github/penguinman-99/Python_AI/blob/main/MypythonAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi


Fri Feb  5 09:40:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    11W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import tensorflow as tf
import numpy as np
# string=tf.Variable("this is a string", tf.string)
# number=tf.Variable(324,tf.int16)
# floating=tf.Variable(3.567,tf.float64)
#a=tf.zeros([2,10]) #2행 10열, 0으로 초기화
#b=tf.eye(3) #대각선 값만 1로 고정



텐서플로우는 사칙연산을 지원하지만 배열크기와 shape이 같아야 연산가능 

In [ ]:
#reduce 함수: 행렬합, 평균, 최대값,최소값 구하기 
a=tf.constant([1,2,3,4,5,6,7,8,9,10])
print(tf.reduce_sum(a))
print(tf.reduce_mean(a))
print(tf.reduce_max(a))
print(tf.reduce_min(a))
c=a+5
print(c)

tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([ 6  7  8  9 10 11 12 13 14 15], shape=(10,), dtype=int32)


In [6]:
#행렬의 곱 계산

first=tf.constant([[1,2,3],[4,5,6]])
second=tf.constant([[10,11],[20,21],[30,31]])
c=tf.matmul(first,second)
print(c)
#d=tf.add(first,second)
#print(d)
#덧셈은 행,열이 모두 같아야한다.


tf.Tensor(
[[140 146]
 [320 335]], shape=(2, 2), dtype=int32)


In [ ]:
#Reshape 함수: Tensor의 형태를 바꾼다.

e=tf.reshape(second,[2,3])
d=tf.add(e,first)
print(d)

#cast: 데이터 타입을 바꾼다.
A=tf.constant([[1,2,3],[4,5,6]])
B=tf.constant([[10.1,11],[20,30],[30,31]])
print(A)
print(B)

C=tf.cast(A,tf.float32)
D=tf.reshape(C,[3,2])
print(tf.add(D,B))


In [31]:
ex1=tf.constant([[1,2,3],[4,5,6]])
ex2=tf.constant([[10,11],[20,21],[30,31]])

print(ex2)
#Slice: 일부만 복사
result=tf.slice(ex2,[0,0],[1,2])
print(result)

tf.Tensor(
[[10 11]
 [20 21]
 [30 31]], shape=(3, 2), dtype=int32)
tf.Tensor([[10 11]], shape=(1, 2), dtype=int32)


In [37]:
#텐서를 합치기 concat, stack

A=tf.constant([[1,1],[2,2],[3,3]])
B=tf.constant([[10,10],[20,20],[30,30]])
print(A)
print(B)
#0:행기준
D=tf.concat([A,B],0)
D1=tf.concat([A,B],1)
#1: 열기준
print(D)
print(D1)

#stack: 차원을 하나 더 늘리고, 정해진 행 열기준에 따라 합쳐줌

E=tf.stack([A,B],0)
E1=tf.stack([A,B],1)
print(E)
print(E1)

tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10 10]
 [20 20]
 [30 30]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  1]
 [ 2  2]
 [ 3  3]
 [10 10]
 [20 20]
 [30 30]], shape=(6, 2), dtype=int32)
tf.Tensor(
[[ 1  1 10 10]
 [ 2  2 20 20]
 [ 3  3 30 30]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[ 1  1]
  [ 2  2]
  [ 3  3]]

 [[10 10]
  [20 20]
  [30 30]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[ 1  1]
  [10 10]]

 [[ 2  2]
  [20 20]]

 [[ 3  3]
  [30 30]]], shape=(3, 2, 2), dtype=int32)
